hash-format = "sha256"

[[files]]
file = "mods/advancement-plaques.pw.toml"
hash = "d3a87d340439309a208ec67f0d9c8004458b315f39add685ee298909988f0d9b"
metafile = true

[[files]]
file = "mods/advancements-debug.pw.toml"
hash = "f6620ab34805ef3a7c88b8a83c044e69f15c2034af90bd55820041469e8357fa"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "f30b15dc574856f6eca824f645537680ca12a6282bee89a33cbced66d6601dca"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "65b0ccc80e7bb51344fc138cfe952a6c9cfea23db0282a8852799be0cca29b85"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4d571d5ebe245ffb62a0df83e81d1c03670807d3528650d6dd9c983bd26ae860"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ff2b30a400a50042f2562cb86b5ecd7b24ae1b747fea712fa4001dc674ff3ed1"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "63edbd012db544d0590a1cd2563a4973c0316b8033370b41a48c05b0e8e667e5"
metafile = true

[[files]]
file = "mods/bedrockwaters.pw.toml"
hash = "e143f0581d9a5079eef15faa984c73f8b242d7a54c0472b1ed461789eb91241b"
metafile = true

[[files]]
file = "mods/better-enchanted-books.pw.toml"
hash = "345789b47f582c6b93f3266185133e29f233e91078ddcf245847360cf89781e0"
metafile = true

[[files]]
file = "mods/block_limit_fix.pw.toml"
hash = "c1f2120122972062a6e4be666e432b4a748eabdc977e801b3d7db9f974a05145"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "e8ccaa2816d767744121e3240a30bb061f8bba8c9274909017832d2f8576ce50"
metafile = true

[[files]]
file = "mods/camera-utils.pw.toml"
hash = "a3326c6be394dd05dc7758f6187a4e2ddd416fd47b387ea40eef180c65b5ea7e"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
hash = "b2bc57658f23e8ece8c061fbdbb79b6da90ffd607992566a3e547ef3215de79e"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "f8d3e3dc160497e5f419565447a24e888e612fae12557d9adc8ecb8355dd0f7c"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "46b444dc88aac495a314699961072c72b16661130aff501d176a2b8c12c49b72"
metafile = true

[[files]]
file = "mods/charm.pw.toml"
hash = "ff8960a3bf63e66854c676cf1db8b88c6666bc526e3d3562be297d94c528472a"
metafile = true

[[files]]
file = "mods/charmonium.pw.toml"
hash = "ccc10f99cb19427bbe111efeecce5c2934a02d4294b2fedc3ef1e7fdc60771d3"
metafile = true

[[files]]
file = "mods/chatcalc.pw.toml"
hash = "e263dd37f7bb2af931ff0538efb69938fc72baa256eefa536645e6a6b314b986"
metafile = true

[[files]]
file = "mods/clearnetherrack.pw.toml"
hash = "54d5b9bad71f7ce225ecb4163dfcd3ddce145fa99990443445f201f3749357db"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "1a4c9d83b0709fd2f91814eb67f81e19bb1493315c42cb65efe911d0f34c5a13"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "213cad77d46ff46fe20780b01856cb1a8812747e9c3564203669bf3905e646e2"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "84070bb5bd5ac094b111c08dcafdfa71e885c4cb5187097615e7b5ad2b6ebac8"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "b1aa83bed8ef891dff38190701b48f6dd70085c26159f9316334bbe85b935ead"
metafile = true

[[files]]
file = "mods/crops-love-rain.pw.toml"
hash = "e6ce78af13cd662ab6dedf5c67d8b9d9210b66242593cf1be08f45ed935d4af7"
metafile = true

[[files]]
file = "mods/dimthread.pw.toml"
hash = "edf4d6024ba380cc5e3d308da2077a22288b03e9ac465000d604fa5df0241911"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "1bba2574a2f04ba8c037eaaa8f4b599176f20e1a5f144ee6eb55725fabdc7e44"
metafile = true

[[files]]
file = "mods/dynamiccrosshaircompat.pw.toml"
hash = "4fc3621536598066816efe338f7154b0d0f0d1e97354b5827298470b5cb53733"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "bf886d03a194a4036f02afe690cb21ca346fff20f4193355994ec97f046a8809"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
hash = "26ce46903b0f7c33c0d54f20967ded566fbc9910d72151810b2eb7e475077c7b"
metafile = true

[[files]]
file = "mods/extraalchemy.pw.toml"
hash = "5031d54b22478641c4f70b444ce533e342c81d86e08df6c8072a032235a817f0"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "bdc0026a453334abaa888c085ea5f34c7a818406a79b8c4702d5345f883787cb"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "0fe83c99b29c952f464c7bfba9cc86cc4f834bef7834821433fe23ce3dd230e6"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
hash = "b8d91a91ac8820ed7c99c12636c7de0a3e93ef825c1925d4a9287b443cd65f92"
metafile = true

[[files]]
file = "mods/fast-portals.pw.toml"
hash = "34a117be86b8a8610cded7018c82da3a91610e827c8f2a52cb62f1002db22b75"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "98da553a1ba2d41bfce3585198641c2d927c702d5403ebec82402ae51ddf707f"
metafile = true

[[files]]
file = "mods/forgetmechunk.pw.toml"
hash = "c576911c18870a36c1337d4f48b708fb620b51f1cb0c6497e5cab661ae07f5a0"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "efcc25b88be11ae20eb1deefd9cdf49e26a08f4d18cc9b0bbb6b172b404e5ff3"
metafile = true

[[files]]
file = "mods/gotta-go-fast-fabric.pw.toml"
hash = "1f202c03d7e9bb50f0c548336fe47c6f37d8f4d39907c243cab782de87dccc25"
metafile = true

[[files]]
file = "mods/hotbarcycle.pw.toml"
hash = "3d37f23b0a16f8378663b30f6ea17467564506323aefd27fc6ee8bf18a9adbef"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "a81c6e60f18faf727ed743029c8a4d093c6c96f0c450be7bf3535985ee6f4288"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e8168531c092676d47cac3657bfc525f096f11ff5372ce6e322ad57778b81635"
metafile = true

[[files]]
file = "mods/interactic.pw.toml"
hash = "d4f85fc72da9cf35b73a202df5b2ac94fa6649bff03081111abfa3080e315969"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "b7ddb84e65bee3c1f60bc9a917f0f31130b379a50feb60fae49898948184ffe8"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "34ed93489f0523da09080c7e75bfb060515e7bbe0cdc60f450495ba3946ddee3"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "3c95ba1c0a5e8065fbce03ea38aef44e5dfdff2e681c81a8720e6ff543774309"
metafile = true

[[files]]
file = "mods/kitsune.pw.toml"
hash = "45ef4adfac4082e0f6262e9b46cdbe4da918ab73d2eac99ab03eb0c44703ef07"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "998f45a9037fa4663bc5e2bea5de925bf4ce6352328fcaaa830db8466cc62416"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "507abebf9ae5282c92a1c799ed9666e23f0605190633c16e086b1c9e17ad4465"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9b628c73b749c901f12ba08b8304c161801903b1dd3fdbb6d4b93a9d42d25afa"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "cbd6b97dfc49090b18480f43eeef4401144006ed406110f32fb1126d47a21f11"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "e4958dc5dc67d3595710ee4b644edd1bed50eecf2fd990949487d47999e40729"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "730a2942abc26467602f541397824c3d0f8cfb2d497f2239ec72d98f9c10fbe9"
metafile = true

[[files]]
file = "mods/libre-exp-fix.pw.toml"
hash = "6453f82b633c8d181650f4eef6b35c17a40a90cb60ba123248243fe0a4e6d338"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "28b3808ae3e3e5bcc8f2a6dfe40c539a2e55afd3687e41c681dc408021e395ef"
metafile = true

[[files]]
file = "mods/log-begone.pw.toml"
hash = "9d388726243ba4646a212a3131df5b4b69ee1b41b89c86ebaea960093b6bf79e"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "2f1393d78824d3e665be954e339affed26d8482d227aa3f13d6ca5d577469f8b"
metafile = true

[[files]]
file = "mods/microdurability.pw.toml"
hash = "2c44f182a7875bcb8447c004078c79c4f7bad9ec3ccfe63586f2127f1fa74a58"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "b89656eaf7e4404d8d2c5b1e1155aae85a839939f83cab6d1b5e791412ad5f86"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "be0fd8b9cd9f8a94428ea8ac5ec84f4f7bab23697236b7a2e54d8537834e0315"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "79e31e1697a4121696b9a1817ff75ebe58af1514f132cdc64522d4ca4e0cdd08"
metafile = true

[[files]]
file = "mods/morecullingextra.pw.toml"
hash = "ad85600fddb58af75bee8cbf6807ac9b0bf0d57a2a963da8a57f77e80fe275b7"
metafile = true

[[files]]
file = "mods/origins-classes.pw.toml"
hash = "8a1fd17d88e7fd25c3a6b819e7899ee2826da99a46d0920d7b6157eba9d57505"
metafile = true

[[files]]
file = "mods/origins-plus-plus.pw.toml"
hash = "3b7c7ab03dba66dbe7216ac8e34965f51bdcd8b78f14a70254b175e269a65703"
metafile = true

[[files]]
file = "mods/origins-umbrellas.pw.toml"
hash = "db7eb9490bf80d0c26330a1e0d97227c13b41ba849f3618521547a84bce20162"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
hash = "93d172828f186dcd1367a69f01b3f291302320fe6cc91e81e29bae9c6f857011"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "bb7a3fce6f6350212dd0460fd73f2a25c44f0789331faabd5e6b14e60713711f"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "8134c08af1ac4d5c8aef4b134d205fb12b202c2a6ad323cc93b7bb8ada19de21"
metafile = true

[[files]]
file = "mods/reacharound.pw.toml"
hash = "afedc35545eb5be295caee5e0cac50de9941e4487a1a78d54ead98cc69110843"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b2e3be698473bfb3f08865a11e74c9ee8d47239ac72a79d60acc1ee381722a50"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "7ce4e1730767749737ed344affc23dc397840d0ff77e7b2942fecf349bd22529"
metafile = true

[[files]]
file = "mods/roughly-enough-loot-tables.pw.toml"
hash = "d6696013c9c6bafa947b8e998124080bb41c97fe89d1c91098ca1dbec3350e37"
metafile = true

[[files]]
file = "mods/roughly-enough-professions-rep.pw.toml"
hash = "7f67f250f1ac5f71b62d9682db7e99fc1652271ad574dce12a295ab148cc8e2c"
metafile = true

[[files]]
file = "mods/roughly-enough-resources.pw.toml"
hash = "6f46cfcca55777b06ce0bf646a815aed4fbc4eb19e21e055a8e6528e41397278"
metafile = true

[[files]]
file = "mods/roughly-enough-trades.pw.toml"
hash = "253d24d518bf1c952361a25e91d1c80d0c30f83a47c8a94a05bdf8d51a6e97a9"
metafile = true

[[files]]
file = "mods/scout.pw.toml"
hash = "10886b2438dab2be9b49c79eaf099771e526246f06c2a382ef56100bbcc73077"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "94d8491cd39504b6faa3fb1c3da6233dfc0dbf5d854798a53079fb3f7c5fdfd0"
metafile = true

[[files]]
file = "mods/sessility.pw.toml"
hash = "830d8b3268f6379b7746b54ad8d71ee043010b508f78de7c9cba138dbfe22be0"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "9c08011eaed91ca490a032279dd468d414a0153db6d8d24438a9cbf5a162d1bb"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "c7099714e081561e8a2f2b29cf3b2a1e397bb5a7c8ce313f8fcd15316363e600"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "971e8b0bef16bd6ce88c7f940b30fdc1debff7b715058f4d331d54beb58a4314"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8da0d4c285e7e57aee3f08ab4e268d04518704ace4060744f042aef3a7f6bc50"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "3b3f8dad7310746ff9a80092827faf48d284121c54399504be46c0da9d9ca508"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "2aeab4f3b0a720ed02f400d9b521f1858474d4f8f7c3577ce916d5aa31fe37e1"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "ab907ea5653d8869c147fea450bb1d553a85bc31b5f323bccb00b359533dabc6"
metafile = true

[[files]]
file = "mods/status.pw.toml"
hash = "afee7fa20bd4e7d59f7ffd0765fa9dd3c189fc5713356b571d01373623f7bcdf"
metafile = true

[[files]]
file = "mods/stepup.pw.toml"
hash = "f4c40da8fc378013420d86fbdd3663f16cc8b8941be0ca18a61d8eac943c0ce7"
metafile = true

[[files]]
file = "mods/tfl-utils.pw.toml"
hash = "6816d90d81c186de7a84b47c327d925ab7131d8251933dd1affb80bb21e5bed6"
metafile = true

[[files]]
file = "mods/timeoutout.pw.toml"
hash = "79bf46f1892bfb23ff9a69b16d0f9147da33809021f0f2ef2f73ae7d10bbefec"
metafile = true

[[files]]
file = "mods/too-many-binds.pw.toml"
hash = "377dbb87db55f7a1062f8fd67e98ab2547b095fea056bb4d08ad54639ba3fff1"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "4f782435d758d3cfd57ba49e2a4994006722d42307ef74ef3d35a1704f9ed5c4"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "e4e021f4e9647d01496dfd9f4dbf77cf46575318bd54f40aac7d3b4996baecb8"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
hash = "89b25533c6a11961a4640f4f3cd1c6dbf4678e101423c1dbb02c1a6386fdc707"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "151a53057bd6f757ff073dd8f8344b354f872f0dc4d236daad3fffea5de0b7dc"
metafile = true

[[files]]
file = "mods/wdmgslt.pw.toml"
hash = "8b573a7962316028e8ad10fd7386ce2e03569aa9258c5624a24490f3b068418e"
metafile = true

[[files]]
file = "mods/windchimes.pw.toml"
hash = "da56f8d502498b731410138e36d618600fc7c3bff2d99cb342af1c6ef9840823"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "4a781874847eb651d839e150d3e0429f81b7ff5462065ace6679a2e193340b01"
metafile = true

[[files]]
file = "mods/xl-packets-fabric.pw.toml"
hash = "2c3859d6f191e9f1761b29fe6886635e0e84466681f0d526b08b16fa177a6a2f"
metafile = true

[[files]]
file = "unsup-0.2.0-pre3.jar"
hash = "c5bd49784392b651e4bc71fe57976f5b4fb14f09e0e23183ae5b94a821ae4756"

[[files]]
file = "unsup.ini"
hash = "622d068d1529a6586343573232b797f745f8eb31c668bd092c3bf6b81e504a9f"
