[flavor_groups.misc]
name = "Miscelaneus"
description = "Miscelaneus mods that do not quite fit a propper group"
side = "client"
choices = [ "misc_on", "misc_off",]

[metafile.additional-structures-fabric]
flavors = "misc_on"

[metafile.advancement-plaques-fabric]
flavors = "misc_on"

[metafile.alternate-current]
flavors = "misc_on"

[metafile.amecs]
flavors = "misc_on"

[metafile.another-furniture]
flavors = "misc_on"

[metafile.appleskin]
flavors = "misc_on"

[metafile.architects-palette-fabric]
flavors = "misc_on"

[metafile.architectury-api]
flavors = "misc_on"

[metafile.backpacked-fabric]
flavors = "misc_on"

[metafile.bad-log-remover]
flavors = "misc_on"

[metafile.balm-fabric]
flavors = "misc_on"

[metafile.bartering-station]
flavors = "misc_on"

[metafile.better-advancements]
flavors = "misc_on"

[metafile.better-potion-visuals]
flavors = "misc_on"

[metafile.better-stats]
flavors = "misc_on"

[metafile.camera-utils]
flavors = "misc_on"

[metafile.charmonium]
flavors = "misc_on"

[metafile.chimes]
flavors = "misc_on"

[metafile.chipped]
flavors = "misc_on"

[metafile.choicetheorems-overhauled-village]
flavors = "misc_on"

[metafile.cleancut]
flavors = "misc_on"

[metafile.cloth-config]
flavors = "misc_on"

[metafile.clumps]
flavors = "misc_on"

[metafile.collective]
flavors = "misc_on"

[metafile.compact-help-command]
flavors = "misc_on"

[metafile.connectivity]
flavors = "misc_on"

[metafile.content-creator-server-status]
flavors = "misc_on"

[metafile.corgilib]
flavors = "misc_on"

[metafile.couplings]
flavors = "misc_on"

[metafile.create-deco-fabric]
flavors = "misc_on"

[metafile.create-enchantment-industry-fabric]
flavors = "misc_on"

[metafile.create-fabric]
flavors = "misc_on"

[metafile.create-steam-n-rails]
flavors = "misc_on"

[metafile.creativecore]
flavors = "misc_on"

[metafile.ctm-refabricated]
flavors = "misc_on"

[metafile.cultural-delights-fabric]
flavors = "misc_on"

[metafile.daves-potioneering]
flavors = "misc_on"

[metafile.debugify]
flavors = "misc_on"

[metafile.decorative-blocks]
flavors = "misc_on"

[metafile.delightful-creators-fabric]
flavors = "misc_on"

[metafile.ecologics]
flavors = "misc_on"

[metafile.effective]
flavors = "misc_on"

[metafile.entityculling]
flavors = "misc_on"

[metafile.every-compat]
flavors = "misc_on"

[metafile.expanded-delight]
flavors = "misc_on"

[metafile.explorify]
flavors = "misc_on"

[metafile.fabric-api]
flavors = "misc_on"

[metafile.fabric-language-kotlin]
flavors = "misc_on"

[metafile.falling-leaves-fabric]
flavors = "misc_on"

[metafile.farmers-delight-fabric]
flavors = "misc_on"

[metafile.farmers-knives]
flavors = "misc_on"

[metafile.ferritecore-fabric]
flavors = "misc_on"

[metafile.findme]
flavors = "misc_on"

[metafile.forge-config-api-port-fabric]
flavors = "misc_on"

[metafile.framework-fabric]
flavors = "misc_on"

[metafile.free-cam]
flavors = "misc_on"

[metafile.fusion-connected-textures]
flavors = "misc_on"

[metafile.geckolib]
flavors = "misc_on"

[metafile.iceberg-fabric]
flavors = "misc_on"

[metafile.image2map]
flavors = "misc_on"

[metafile.immersive-structures]
flavors = "misc_on"

[metafile.immersive-structures-ii-nether-edition]
flavors = "misc_on"

[metafile.indium]
flavors = "misc_on"

[metafile.inventory-profiles-next]
flavors = "misc_on"

[metafile.itemphysic-lite]
flavors = "misc_on"

[metafile.itemswapper]
flavors = "misc_on"

[metafile.javd]
flavors = "misc_on"

[metafile.kitsune]
flavors = "misc_on"

[metafile.kubejs]
flavors = "misc_on"

[metafile.kubejs-create]
flavors = "misc_on"

[metafile.lambdabettergrass]
flavors = "misc_on"

[metafile.lambdynamiclights]
flavors = "misc_on"

[metafile.lazydfu]
flavors = "misc_on"

[metafile.ledger]
flavors = "misc_on"

[metafile.ledger-databases]
flavors = "misc_on"

[metafile.legendary-tooltips-fabric]
flavors = "misc_on"

[metafile.libipn]
flavors = "misc_on"

[metafile.light-overlay]
flavors = "misc_on"

[metafile.lithium]
flavors = "misc_on"

[metafile.log-begone]
flavors = "misc_on"

[metafile.memoryleakfix]
flavors = "misc_on"

[metafile.microdurability]
flavors = "misc_on"

[metafile.minimotd]
flavors = "misc_on"

[metafile.missing-wilds]
flavors = "misc_on"

[metafile.mixintrace]
flavors = "misc_on"

[metafile.modmenu]
flavors = "misc_on"

[metafile.mru]
flavors = "misc_on"

[metafile.natures-compass]
flavors = "misc_on"

[metafile.netherportalfix-fabric]
flavors = "misc_on"

[metafile.nethers-delight-fabric]
flavors = "misc_on"

[metafile.oh-the-biomes-youll-go-fabric]
flavors = "misc_on"

[metafile.origins]
flavors = "misc_on"

[metafile.origins-classes]
flavors = "misc_on"

[metafile.origins-plus-plus]
flavors = "misc_on"

[metafile.origins-umbrellas]
flavors = "misc_on"

[metafile.owo-lib]
flavors = "misc_on"

[metafile.pehkui]
flavors = "misc_on"

[metafile.prism-fabric]
flavors = "misc_on"

[metafile.puzzles-lib]
flavors = "misc_on"

[metafile.reacharound]
flavors = "misc_on"

[metafile.rechiseled]
flavors = "misc_on"

[metafile.rechiseled-create]
flavors = "misc_on"

[metafile.reeses-sodium-options]
flavors = "misc_on"

[metafile.resourceful-lib]
flavors = "misc_on"

[metafile.rhino]
flavors = "misc_on"

[metafile.roughly-enough-items]
flavors = "misc_on"

[metafile.roughly-enough-loot-tables]
flavors = "misc_on"

[metafile.roughly-enough-professions-rep]
flavors = "misc_on"

[metafile.roughly-enough-resources]
flavors = "misc_on"

[metafile.roughly-enough-trades]
flavors = "misc_on"

[metafile.satin-api]
flavors = "misc_on"

[metafile.selene]
flavors = "misc_on"

[metafile.server-hats]
flavors = "misc_on"

[metafile.servercore]
flavors = "misc_on"

[metafile.shulkerboxtooltip]
flavors = "misc_on"

[metafile.simple-voice-chat]
flavors = "misc_on"

[metafile.sleep-warp]
flavors = "misc_on"

[metafile.slice-and-dice]
flavors = "misc_on"

[metafile.smooth-boot]
flavors = "misc_on"

[metafile.snow-under-trees-remastered]
flavors = "misc_on"

[metafile.sodium]
flavors = "misc_on"

[metafile.sodium-extra]
flavors = "misc_on"

[metafile.spark]
flavors = "misc_on"

[metafile.starlight]
flavors = "misc_on"

[metafile.status-effect-bars]
flavors = "misc_on"

[metafile.supermartijn642s-config-lib]
flavors = "misc_on"

[metafile.supermartijn642s-core-lib]
flavors = "misc_on"

[metafile.terrablender-fabric]
flavors = "misc_on"

[metafile.the-twilight-forest]
flavors = "misc_on"

[metafile.towns-and-towers]
flavors = "misc_on"

[metafile.trading-post]
flavors = "misc_on"

[metafile.trinkets]
flavors = "misc_on"

[metafile.twilight-origins]
flavors = "misc_on"

[metafile.underwater-enchanting]
flavors = "misc_on"

[metafile.visuality]
flavors = "misc_on"

[metafile.xaeros-minimap]
flavors = "misc_on"

[metafile.xaeros-world-map]
flavors = "misc_on"

[metafile.xl-packets-fabric]
flavors = "misc_on"

[metafile.yacl]
flavors = "misc_on"

[metafile.yosbr]
flavors = "misc_on"

[metafile.youre-in-grave-danger]
flavors = "misc_on"

[metafile.zombie-proof-doors]
flavors = "misc_on"
